### ISSUE TITLE
How to get started? 

### ISSUE THREAD

**Issue by vatsalpb** [chowarth/MyPlayStation.API#1]
Hey I want to use your library to pull game information for the user. I am not sure how to get started. How do I use your API?

**Comment by chowarth** [comment]
Hi @vatsalpb , I have been meaning to put down a brief "How to" but just haven't had the time with work lately 😞 I'll try and take a look today at some point!

**Comment by vatsalpb** [comment]
Thank you

**Comment by chowarth** [comment]
@vatsalpb I've added a brief overview of how to create a service to the readme. I know it's not really in-depth but it should help get started, I need to take a look at the best way to create documentation. Any questions just let me know.
